package ec.ups.edu.pruebaSegundo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-01-20T20:36:15.765-05:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://services.pruebaSegundo.ups.edu.ec/", name = "TituloServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface TituloServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "buscarPersona", targetNamespace = "http://services.pruebaSegundo.ups.edu.ec/", className = "ec.ups.edu.pruebaSegundo.BuscarPersona")
    @ResponseWrapper(localName = "buscarPersonaResponse", targetNamespace = "http://services.pruebaSegundo.ups.edu.ec/", className = "ec.ups.edu.pruebaSegundo.BuscarPersonaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.ups.edu.pruebaSegundo.Persona buscarPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "insertTitulo", targetNamespace = "http://services.pruebaSegundo.ups.edu.ec/", className = "ec.ups.edu.pruebaSegundo.InsertTitulo")
    @ResponseWrapper(localName = "insertTituloResponse", targetNamespace = "http://services.pruebaSegundo.ups.edu.ec/", className = "ec.ups.edu.pruebaSegundo.InsertTituloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String insertTitulo(
        @WebParam(name = "arg0", targetNamespace = "")
        ec.ups.edu.pruebaSegundo.Titulo arg0
    );
}
